Transform: AWS::Serverless-2016-10-31
Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyTaskReminderAPI_Cloudformation
      EndpointConfiguration:
        Types:
          - REGIONAL