Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Cloudformation_MyTaskReminder_EventData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: EventID
          AttributeType: S
      KeySchema:
        - AttributeName: EventID
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  DynamoDBTable:
    Value: !Ref DynamoDBTable
    Export:
      Name: DynamoDBTable
  DynamoDBTableStreamArn:
    Value: !GetAtt DynamoDBTable.StreamArn
    Export:
      Name: DynamoDBTableStreamArn